### ISSUE TITLE
The scraper for the Federal Register of Legislation no longer works

### ISSUE THREAD

**Issue by umarbutler** [umarbutler/open-australian-legal-corpus-creator#1]
The Federal Register of Legislation recently upgraded their website, thereby breaking its scraper. This requires the scraper to be entirely refactored as their new website employs a much different public API.

**Comment by umarbutler** [comment]
Resolved by #c01b1d8 which has been added to v1.0.1.

**Comment by jacobcd** [comment]
The federal_court_of_australia scraper fails with a ClientConnectorDNSError when attempting to connect to search2.fedcourt.gov.au:443. DNS resolution returns NXDOMAIN, indicating that the endpoint is no longer valid. This breaks the scraper for Federal Court decisions.

Is there an alternative?

**Comment by umarbutler** [comment]
@jacobcd thanks for reporting this bug, I've just fixed it :) For future reference, please create a new issue instead of commenting an existing one the next time you have a problem that is not relevant to the issue being commented on, it makes easier it for maintainers to track.
