### ISSUE TITLE
permission to use for research

### ISSUE THREAD

**Issue by eehsan** [umarbutler/open-australian-legal-corpus-creator#3]
Hi Umar, this is a superb resource. Are we allowed to use this data for research, or we require to seek permission from each jurisdictions again? I understand this is now open-sourced, but it appears that each jurisdiction has its own policy on data access and redistribution and I am not sure if the permission they granted to you would transfer to others as well. If you could include a clarification in your license term or the readme.md, it would be highly appreciated. Thank you.

**Comment by umarbutler** [comment]
Hi @eehsan,
This code is completely openly licensed under the MIT licence, however, you do need permissions from the various sources to **scrape** their data. It, however, sounds like you just want to use the data, and if that is the case, then you can certainly use it for research. The dataset is available [here](https://huggingface.co/datasets/umarbutler/open-australian-legal-corpus) and the licences are available [here](https://huggingface.co/datasets/umarbutler/open-australian-legal-corpus/blob/main/LICENCE.md).

**Comment by eehsan** [comment]
Hi @umarbutler, do you happen to also have the raw crawled files (i.e., htmls/rtf/docs) by any chance? The released pre-processed version has flattened some of the useful structures.
